server-url: http://relex-coin.relex.ru:7766/api

server:
  http2:
    enabled: true
  servlet:
    context-path: /api
  port: 7766

spring:
  profiles:
    active: production
  sql:
    init:
      mode: always
      separator: ^^^ END OF SCRIPT ^^^
  application:
    name: flutter_test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_flutter:5432/flutter
    username: postgres
    password: 123321
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

logging:
  level:
    com.example.flutter: DEBUG
#    org.springframework.security: TRACE