server-url: http://localhost:7766/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flutter
    username: postgres
    password: 123321
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
#        generate_statistics: true
        format_sql: true